//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyTiger.Mapper {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlyTiger.Mapper.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Add Mapper 的本地化字符串。
        /// </summary>
        internal static string AddMapper {
            get {
                return ResourceManager.GetString("AddMapper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not map property &apos;{0}&apos; from &apos;{1}&apos; to &apos;{2}&apos; 的本地化字符串。
        /// </summary>
        internal static string CanNotMapProperty_Description {
            get {
                return ResourceManager.GetString("CanNotMapProperty_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not map property 的本地化字符串。
        /// </summary>
        internal static string CanNotMapProperty_MessageFormat {
            get {
                return ResourceManager.GetString("CanNotMapProperty_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not map property 的本地化字符串。
        /// </summary>
        internal static string CanNotMapProperty_Title {
            get {
                return ResourceManager.GetString("CanNotMapProperty_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Duplicate mapper 的本地化字符串。
        /// </summary>
        internal static string DuplicateMapper_Description {
            get {
                return ResourceManager.GetString("DuplicateMapper_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Duplicate mapper from &apos;{0}&apos; to &apos;{1}&apos; 的本地化字符串。
        /// </summary>
        internal static string DuplicateMapper_MessageFormat {
            get {
                return ResourceManager.GetString("DuplicateMapper_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Duplicate mapper 的本地化字符串。
        /// </summary>
        internal static string DuplicateMapper_Title {
            get {
                return ResourceManager.GetString("DuplicateMapper_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The mapper is not being used, can be removed 的本地化字符串。
        /// </summary>
        internal static string MapperNotUsed_Description {
            get {
                return ResourceManager.GetString("MapperNotUsed_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The mapper from &apos;{0}&apos; to &apos;{1}&apos; is not being used, can be removed 的本地化字符串。
        /// </summary>
        internal static string MapperNotUsed_MessageFormat {
            get {
                return ResourceManager.GetString("MapperNotUsed_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The mapper is not being used 的本地化字符串。
        /// </summary>
        internal static string MapperNotUsed_Title {
            get {
                return ResourceManager.GetString("MapperNotUsed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Missing mapper 的本地化字符串。
        /// </summary>
        internal static string MissingMapper_Description {
            get {
                return ResourceManager.GetString("MissingMapper_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Missing mapper &apos;{0}&apos; to &apos;{1}&apos; 的本地化字符串。
        /// </summary>
        internal static string MissingMapper_MessageFormat {
            get {
                return ResourceManager.GetString("MissingMapper_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Missing mapper 的本地化字符串。
        /// </summary>
        internal static string MissingMapper_Title {
            get {
                return ResourceManager.GetString("MissingMapper_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove Mapper 的本地化字符串。
        /// </summary>
        internal static string RemoveMapper {
            get {
                return ResourceManager.GetString("RemoveMapper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Source property is not mapped 的本地化字符串。
        /// </summary>
        internal static string SourcePropertyNotMapped_Description {
            get {
                return ResourceManager.GetString("SourcePropertyNotMapped_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Source property &apos;{0}&apos; in class &apos;{1}&apos; is not mapped, target class is &apos;{2}&apos;. 的本地化字符串。
        /// </summary>
        internal static string SourcePropertyNotMapped_MessageFormat {
            get {
                return ResourceManager.GetString("SourcePropertyNotMapped_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Source property is not mapped 的本地化字符串。
        /// </summary>
        internal static string SourcePropertyNotMapped_Title {
            get {
                return ResourceManager.GetString("SourcePropertyNotMapped_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target property is not filled 的本地化字符串。
        /// </summary>
        internal static string TargetPropertyNotFilled_Description {
            get {
                return ResourceManager.GetString("TargetPropertyNotFilled_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target property &apos;{0}&apos; in class &apos;{1}&apos; is not filled, source class is &apos;{2}&apos;. 的本地化字符串。
        /// </summary>
        internal static string TargetPropertyNotFilled_MessageFormat {
            get {
                return ResourceManager.GetString("TargetPropertyNotFilled_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target property is not filled 的本地化字符串。
        /// </summary>
        internal static string TargetPropertyNotFilled_Title {
            get {
                return ResourceManager.GetString("TargetPropertyNotFilled_Title", resourceCulture);
            }
        }
    }
}
