//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlyTiger.CodeException {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Code {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Code() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlyTiger.CodeException.Code", typeof(Code).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 using System;
        ///namespace FlyTiger.CodeException
        ///{
        ///    [Serializable]
        ///    class CodeException : Exception
        ///    {
        ///        public CodeException(string code) : base()
        ///        {
        ///            this.Code = code;
        ///        }
        ///        public CodeException(string code, string message) : base(message)
        ///        {
        ///            this.Code = code;
        ///        }
        ///        public CodeException(string code, string message, Exception inner) : base(message, inner)
        ///        {
        ///            this.Code = code;
        ///        }
        ///        pub [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string CodeException {
            get {
                return ResourceManager.GetString("CodeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using System;
        ///
        ///namespace FlyTiger
        ///{
        ///    [AttributeUsage(AttributeTargets.Property | AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
        ///    class CodeExceptionAttribute : Attribute
        ///    {
        ///        public CodeExceptionAttribute(string code, string message)
        ///        {
        ///            this.Code = code;
        ///            this.Message = message;
        ///        }
        ///        public string Code { get; private set; }
        ///        public string Message { get; private set; }
        ///    }
        ///} 的本地化字符串。
        /// </summary>
        internal static string CodeExceptionAttribute {
            get {
                return ResourceManager.GetString("CodeExceptionAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using System;
        ///
        ///namespace FlyTiger
        ///{
        ///    [AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
        ///    class CodeExceptionsAttribute : Attribute
        ///    {
        ///        public string CustomTemplate { get; set; }
        ///        public string CodePrefix { get; set; }
        ///        public string ResourceBaseName { get; set; }
        ///        public bool IncludeExceptionData { get; set; } = true;
        ///    }
        ///} 的本地化字符串。
        /// </summary>
        internal static string CodeExceptionsAttribute {
            get {
                return ResourceManager.GetString("CodeExceptionsAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using System;
        ///using System.Collections;
        ///using System.Collections.Generic;
        ///using System.Globalization;
        ///using System.Linq;
        ///using System.Text;
        ///
        ///namespace FlyTiger.CodeException
        ///{
        ///    class TextValuesFormatter
        ///    {
        ///        private const string NullValue = &quot;[null]&quot;;
        ///        private static readonly char[] FormatDelimiters = { &apos;,&apos;, &apos;:&apos; };
        ///        private readonly string _format;
        ///        private readonly List&lt;string&gt; _valueNames = new List&lt;string&gt;();
        ///
        ///        public TextValuesFormatter(string forma [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string TextValuesFormatter {
            get {
                return ResourceManager.GetString("TextValuesFormatter", resourceCulture);
            }
        }
    }
}
