title: FlyTiger
# Set a path/url to a logo that will be displayed instead of the title
logo: "https://raw.githubusercontent.com/yscorecore/ys.knife/master/res/icon.png"
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-remote-theme
exclude: 
  - README.md 
  - Dockerfile
  - docker-compose.yml

# Aux links for the upper right navigation
aux_links:
  "GitHub":
    - "//github.com/yscorecore/flytiger"

# Footer content 
back_to_top: true
back_to_top_text: "Back to top"

# appears at the bottom of every page's main content
footer_content: "Copyright &copy; 2021-2022 Pengbo Yang. Distributed by an <a href=\"https://github.com/yscorecore/flytiger/tree/master/LICENSE.txt\">MIT license.</a>"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/yscorecore/flytiger" # the github URL for your repo
gh_edit_branch: "master" # the branch that your docs is served from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately
theme: jekyll-theme-slate