version: '3'
services:
    jekyll:
        environment:
            - JEKYLL_ENV=docker
        build: .
        ports:
            - "4000:4000"
        command: "serve"
        volumes:
            - "$PWD:/srv/jekyll"